### ISSUE TITLE
?

### ISSUE THREAD

**Issue by jhc-explore** [Explore-AI/edsa_demo_repo#1]
![image](https://user-images.githubusercontent.com/38468637/75010073-edc8d680-5484-11ea-859a-8d6ed3f5b34a.png)

**Comment by JonGerrand** [comment]
Sooo this was created for a Pop-up class within the Academy on 'Using Git and Github'... I thought that having a theme would make the lesson a little bit more entertaining :)

**Comment by jhc-explore** [comment]
Brilliant! :)
